services:
  frontend:
    container_name: frontend
    build:
      context: ./cloudeats-direct/frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - fleet-service
      - inventory-service
      - notification-service
      - order-service
      - payment-service
    networks:
      - cloudeats-network

  fleet-service:
    container_name: fleet-service
    build:
      context: ./services/fleet-service
    ports:
      - "${FLEET_SERVICE_PORT}:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - cloudeats-network

  inventory-service:
    container_name: inventory-service
    build:
      context: ./services/inventory-service
    ports:
      - "${INVENTORY_SERVICE_PORT}:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - cloudeats-network

  notification-service:
    container_name: notification-service
    build:
      context: ./services/notification-service
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - cloudeats-network

  order-service:
    container_name: order-service
    build:
      context: ./services/order-service
    ports:
      - "${ORDER_SERVICE_PORT}:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - cloudeats-network

  payment-service:
    container_name: payment-service
    build:
      context: ./services/payment-service
    ports:
      - "${PAYMENT_SERVICE_PORT}:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - cloudeats-network

  db:
    container_name: cloudeats-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: cloudeats
      POSTGRES_USER: cloudeats
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./services/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cloudeats-network

networks:
  cloudeats-network:
    driver: bridge
