version: '3.9'
services:
  order-service:
    build: ./order-service
    ports:
      - "3000:3000"

  inventory-service:
    build: ./inventory-service
    ports:
      - "3001:3000"

  fleet-service:
    build: ./fleet-service
    ports:
      - "3002:3000"

  payment-service:
    build: ./payment-service
    ports:
      - "3003:3000"

  notification-service:
    build: ./notification-service
    ports:
      - "3004:3000"
